[build]
  publish = "dist"
  command = "npm run build"

[build.environment]
  NODE_VERSION = "18"

# SPA routing - handle all routes
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Domain redirects - redirect non-www to www
[[redirects]]
  from = "https://transitionmarketingai.com/*"
  to = "https://www.transitionmarketingai.com/:splat"
  status = 301
  force = true

[[redirects]]
  from = "http://transitionmarketingai.com/*"
  to = "https://www.transitionmarketingai.com/:splat"
  status = 301
  force = true

[[redirects]]
  from = "http://www.transitionmarketingai.com/*"
  to = "https://www.transitionmarketingai.com/:splat"
  status = 301
  force = true

# Fix MIME type for JavaScript files
[[headers]]
  for = "*.js"
  [headers.values]
    Content-Type = "application/javascript; charset=utf-8"

[[headers]]
  for = "*.mjs"
  [headers.values]
    Content-Type = "application/javascript; charset=utf-8"

[[headers]]
  for = "*.jsx"
  [headers.values]
    Content-Type = "application/javascript; charset=utf-8"

# Security headers
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"